import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className='flex justify-around'>
          <Link href={'/hello'}>Hello</Link>
          <Link href={'/hi/morning'}>Hi/morning</Link>
          <Link href={'/hi/afternoon'}>Hi/afternoon</Link>
          <Link href={'/hi/evening'}>Hi/evening</Link>
        </nav>
        <hr className='border-amber-200' />
        <div className='container mx-auto'>{children}</div>
      </body>
    </html>
  );
}
