services:
  localdb:
    container_name: hana7db
    image: mysql:8.0
    ports:
      - 3309:3306
      - 33080:33090
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
    volumes:
      - ./mysql:/mysql


# mysql -u root -p -h 127.0.0.1 -P 3309
